name: entrance_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  dynamic_height_grid_view: ^0.0.4
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2
  flutter_animate: ^4.5.0
  flutter_easyloading: ^3.0.5
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  talker_dio_logger: ^4.2.0
  permission_handler: ^11.3.1
  lecle_downloads_path_provider: ^0.0.2+8
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons: 
  image_path: assets/icons/icon-app.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
